---
- name: download helm
  copy:
    src: "helm-v3.1.0-rc.1-linux-amd64.tar.gz"
    dest: /tmp/helm.gz
    owner: root
    group: root
    mode: 0644
  when: local == true

- name: download helm
  get_url:
    url: "https://get.helm.sh/helm-v3.1.0-rc.1-linux-amd64.tar.gz"
    dest: /tmp/helm.gz
    owner: root
    group: root
    mode: 0644
  retries: 3
  when: local == false

- name: Unarchive a helm
  unarchive:
    src: /tmp/helm.gz
    dest: /tmp/
    remote_src: yes


- name: copy helm to bin dir
  copy:
    src: /tmp/linux-amd64/helm
    dest: /usr/bin/helm
    remote_src: yes
    owner: root
    group: root
    mode: 0755
  register: helm

- name: add helm repo
  command: helm repo add stable http://mirror.azure.cn/kubernetes/charts/
  when: helm is changed

