---
- name: install k8s
  hosts: k8s
  become: yes

  vars_files:
    - vars/main.yml


  roles:
    - role: hostname
      tags: ['hostname']

    - role: geerlingguy.swap
      tags: ['swap', 'kubernetes']

    - role: geerlingguy.docker
      tags: ['docker']

    - role: geerlingguy.kubernetes
      tags: ['kubernetes']

    - role: pip
      tags: ['pip']

- name: install nfs
  hosts: nfs
  become: yes
  roles:
    - role: ansible-role-nfs
      tags: ['nfs']

- name: set up hosts
  hosts: k8s
  become: yes
  vars_files:
    - vars/nexus.yml
    - vars/jenkins.yml
  roles:
    - role: hosts
      tags: ['hosts']

- name: pre pull images
  hosts: k8s_slaves
  become: yes
  roles:
    - role: docker_images
      tags: ['images']

- name: install helm
  hosts: k8s_master
  become: yes
  vars_files:
    - vars/jenkins.yml
  roles:
    - role: helm
      tags: ['helm']


- name: install infrastructure
  hosts: k8s_master
  become: yes
  vars_files:
    - vars/nexus.yml
    - vars/jenkins.yml
    - vars/gitlab.yml
  roles:
    - role: infrastructure
      tags: ['infrastructure']
