---
- name: install k8s
  hosts: k8s
  become: yes

  vars_files:
    - vars/main.yml


  roles:
    - role: hostname
      tags: ['hostname']

    - role: geerlingguy.swap
      tags: ['swap', 'kubernetes']

    - role: geerlingguy.docker
      tags: ['docker']

    - role: geerlingguy.kubernetes
      tags: ['kubernetes']

- name: install nfs
  hosts: nfs
  become: yes
  roles:
    - role: ansible-role-nfs
      tags: ['nfs']

- name: install helm
  hosts: k8s_master
  become: yes
  vars_files:
    - vars/jenkins.yml
  roles:
    - role: helm
      tags: ['helm']

    - role: jenkins
      tags: ['jenkins']
