---


- name: make sure firewalld stopped
  service:
    name: firewalld
    state: stopped

- name: Join node to Kubernetes master
  shell: >
    {{ kubernetes_join_command }}
    creates=/etc/kubernetes/kubelet.conf
  tags: ['skip_ansible_lint']


