---

- include_tasks: helm_unit.yml
  vars:
    unit_name: nfs-slow
    unit_repo: stable/nfs-client-provisioner
    namespace: default

- include_tasks: helm_unit.yml
  vars:
    unit_name: nfs-fast
    unit_repo: stable/nfs-client-provisioner
    namespace: default

- include_tasks: helm_unit.yml
  vars:
    unit_name: nginx
    unit_repo: stable/nginx-ingress

- include_tasks: helm_unit.yml
  vars:
    unit_name: jenkins
    unit_repo: stable/jenkins
    data:
      jenkins_jobs: "{{ jenkins_jobs }}"
    resources:
      - name: gradle-wrapper
        type: pvc
      - name: npm-cache
        type: pvc-fast
      - name: node-modules-cache
        type: pvc-fast
        data:
          storage: "6Gi"
      - type: secret
        data: "{{ jenkins_data }}"
        name: docker-secret

- include_tasks: helm_unit.yml
  vars:
    unit_name: nexus
    unit_repo: stable/sonatype-nexus

- name: create dns resources
  include_tasks: resource.yml
  vars:
    name: dns
    resource: configmap
    hosts:
      - '{{ docker_ip }} {{ docker_host }}'
      - '{{ nexus_ip }} {{ nexus_host }}'
      - '{{ jenkins_ip }} {{ jenkins_host }}'
      - '{{ gitlab_ip }} gitlab.{{ gitlab_host }}'

- include_tasks: gitlab.yml
  vars:
    unit_name: gitlab
    resources:
      - name: gitlab-shell
        type: service
        data:
          selected_app: gitlab-shell
          namespace: boydfd
          target_port: 2222
          port: 2222
          node_port: "{{ gitlab_shell_port }}"


