kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gradle-cache
  namespace: default
  annotations:
    volume.beta.kubernetes.io/storage-class: nfs-client
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
