---

- name: copy jenkins value yaml
  template:
    src: values.yml
    dest: /root/jenkins.yml
    owner: root
    group: root
    mode: 0755

- name: get jenkins helm status
  shell: helm ls | grep jenkins
  ignore_errors: yes
  register: helm_jenkins

- name: assign label for slave2
  command: kubectl label nodes slave2 jenkins=true
  ignore_errors: yes
  when: helm_jenkins.rc != 0

- name: Ensures pip dir exists
  file: path=~/.pip state=directory

- name: copy pip mirror
  copy:
    src: pip.conf
    dest : ~/.pip/pip.conf

- name: Ensure Pip and dev dependencies are installed.
  package:
    name:
      - python3-pip
      - python36-devel
      - libgit2
      - git
    state: present

- name: Ensure openshift are installed.
  pip:
    name:
      - openshift
    state: present

- name: copy gradle cache pvc yaml
  template:
    src: gradle_cache_pvc.yml
    dest: ~/gradle_cache_pvc.yml

- name: copy gradle wrapper pvc yaml
  template:
    src: gradle_wrapper_pvc.yml
    dest: ~/gradle_wrapper_pvc.yml

- name: require pvc for gradle-cache
  k8s:
    state: present
    src: ~/gradle_cache_pvc.yml

- name: require pvc for gradle-wrapper
  k8s:
    state: present
    src: ~/gradle_wrapper_pvc.yml

- name: install jenkins
  command: helm install jenkins stable/jenkins -f /root/jenkins.yml
  when: helm_jenkins.rc != 0
  retries: 5

