---

- name: copy jenkins value yaml
  template:
    src: values.yml
    dest: /root/jenkins.yml
    owner: root
    group: root
    mode: 0755

- name: get jenkins helm status
  shell: "helm ls -n {{ namespace }}| grep jenkins"
  ignore_errors: yes
  register: helm_jenkins

- name: assign label for slave2
  command: kubectl label nodes slave2 jenkins=true
  ignore_errors: yes
  when: helm_jenkins.rc != 0

- name: Ensures pip dir exists
  file: path=~/.pip state=directory

- name: copy pip mirror
  copy:
    src: pip.conf
    dest : ~/.pip/pip.conf

- name: Ensure Pip and dev dependencies are installed.
  package:
    name:
      - python3-pip
      - python36-devel
      - libgit2
      - git
    state: present

- name: Ensure openshift are installed.
  pip:
    name:
      - openshift
    state: present

- include_tasks: resource.yml
  vars:
    name: "{{ namespace }}"
    resource: namespace

- include_tasks: resource.yml
  vars:
    name: gradle-wrapper
    resource: pvc

- name: install jenkins
  command: helm install jenkins stable/jenkins -f /root/jenkins.yml --namespace boydfd
  when: helm_jenkins.rc != 0
  retries: 5

