---

- name: copy jenkins value yaml
  template:
    src: values.yml
    dest: /root/jenkins.yml
    owner: root
    group: root
    mode: 0755

- name: get jenkins helm status
  shell: "helm ls -n {{ namespace }}| grep jenkins"
  ignore_errors: yes
  register: helm_jenkins

- name: assign label for slave2
  command: kubectl label nodes slave2 jenkins=true
  ignore_errors: yes
  when: helm_jenkins.rc != 0

- name: Ensure openshift are installed.
  pip:
    name:
      - openshift
    state: present

- include_tasks: resource.yml
  vars:
    name: "{{ namespace }}"
    resource: namespace

- include_tasks: resource.yml
  vars:
    name: gradle-wrapper
    resource: pvc

- name: install jenkins
  command: "helm install jenkins stable/jenkins -f /root/jenkins.yml -n {{ namespace }}"
  when: helm_jenkins.rc != 0
  retries: 5

