---

- name: Ensure python docker module are installed.
  pip:
    name:
      - docker
    state: present

- name: pre-pull quay.io/travelaudience/docker-nexus-proxy:2.5.0
  docker_image:
    name: "quay.azk8s.cn/travelaudience/docker-nexus-proxy:2.5.0"
    source: pull

- name: pre-pull quay.io/external_storage/nfs-client-provisioner:v3.1.0-k8s1.11
  docker_image:
    name: "quay.azk8s.cn/external_storage/nfs-client-provisioner:v3.1.0-k8s1.11"
    source: pull
