---
nfs_exports:
  - "/home/rlin/4t-first/public *(rw,sync,no_root_squash)"
  - "/home/rlin/nfs/public *(rw,sync,no_root_squash)"
  - "/home/rlin/nfs/public-async *(rw,async,no_root_squash)"

nfs_rpcbind_state: started
nfs_rpcbind_enabled: true
