---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Docker.
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
  notify: restart docker

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers

- include_tasks: docker-compose.yml
  when: docker_install_compose | bool

- include_tasks: docker-users.yml
  when: docker_users | length > 0

- name: touch docker etc file
  file:
    path: /etc/docker/daemon.json
    state: touch

- name: add docker mirrors local
  lineinfile:
    path: /etc/docker/daemon.json
    regexp: '^\{ "registry-mirrors":'
    line: '{ "registry-mirrors": [ "https://dockerhub.azk8s.cn", "https://hub-mirror.c.163.com" ] }'
    owner: root
    group: root
    mode: '0644'

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: reloaded
